apiVersion: batch/v1
kind: CronJob
metadata:
  name: minute-backup
  namespace: nginx
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: minute-backup
          labels:
            app: minute-backup
        spec:
          containers:
            - name: minute-backup-container
              image: busybox:latest
              command:
                - sh
                - -c
                - >
                  echo "Backup started" ;
                  mkdir -p /backup ;
                  mkdir -p /demo-data ;
                  if [ "$(ls -A /demo-data)" ]; then cp -r /demo-data/* /backup/ ; fi ;
                  echo "Backup completed" ;
              volumeMounts:
                - name: data-volume
                  mountPath: /demo-data
                - name: backup-volume
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: data-volume
              hostPath: 
                path: /demo-data
                type: DirectoryOrCreate
            - name: backup-volume
              hostPath:
                path: /backup
                type: DirectoryOrCreate
